queue_max_size: 4096

tippers_http_sender:
  url: "http://sensoria.ics.uci.edu:8001/observation/add"
  port: 8001
  observation_type: "wemo_energy"

switch_set_maintainer:
  update_interval: 60
  discover_wait_time: 30

switch_querier:
  sensing_interval: 5 
  query_timeout: 10
