tippers_http_sender:
  url: "http://sensoria.ics.uci.edu:8001/resource/observations"
  port: 8001
  observation_type: "wemo_energy"

switch_list_maintainer:
  update_interval: 30
  discover_wait_time: 4

data_collector:
  sensing_interval: 1
